### ISSUE TITLE
Share the binary build between test and release

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#1159] opened 2024-11-26 21:03 UTC
Looks like Pulumi CI builds the provider twice - once for testing and once for actual release, and both become artifacts in GitHub actions. This is not ideal as ideally the same binary that is being tested will be the one released.

**Comment by danielrbradley** [comment] 2024-11-26 21:07
Looks like duplicate of https://github.com/pulumi/ci-mgmt/issues/967

**Closed by danielrbradley** 2024-11-26 21:07 UTC
Labels: resolution/duplicate, kind/enhancement
