### ISSUE TITLE
Address Goreleaser flakes

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/ci-mgmt#878] opened 2024-04-10 16:14 UTC
We have a daily ritual of kicking off re-runs for Go releaser flakes [such as this one](https://github.com/pulumi/pulumi-hcloud/issues/469) and may want to explore adding logic to the workflow to do a retry on a first failure.

**Comment by VenelinMartinov** [comment] 2024-06-13 21:06
duplicate of https://github.com/pulumi/ci-mgmt/issues/816

**Closed by VenelinMartinov** 2024-06-13 21:06 UTC
Labels: resolution/duplicate, kind/engineering
